### ISSUE TITLE
Remove ocean confirmation info

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/ocean-explorer#15]
Number of confirmations does not increase past 1

<img width="1680" alt="Screenshot 2019-08-19 at 11 53 53" src="https://user-images.githubusercontent.com/31970407/63260146-15da4180-c278-11e9-8930-3e489bb61223.png">

**Comment by nkostoulas** [comment]
That's due to caching the result of the RPC once. It would be good to show the correct number (i.e. diff from latest) or remove it completely.

**Comment by tomt1664** [comment]
It would make most sense to remove it completely IMO - more confirmations does not mean it's more secure (like in Bitcoin). 

(we could add the number or Bitcoin confirmations to the Attested field - but this is more complex and a separate feature).
