### ISSUE TITLE
/api

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/ocean-explorer#20]
- [x] /assets #21 

- [x] /asset/:assetid

- [x] /tx

- [x] /block

- [x] /address

- [x] /utxo

- [x] info / status / attestation

**Comment by tomt1664** [comment]
Can we prioritise /status please, so that it is possible for the <redacted>.ch website to get the current block height.

**Comment by tomossomot** [comment]
What should status do exactly?

**Comment by nkostoulas** [comment]
Return Info collection data. I am making a related change for mainstay though so I can do this no worries.

**Comment by nkostoulas** [comment]
You can add `/asset/:assetid` and `/address`, `/utxo`.
