### ISSUE TITLE
Displaying reissuance tokens

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/ocean-explorer#3]
Should they be part of the TX or maybe not show at all

**Comment by tomt1664** [comment]
I think there is no harm in showing them, when they are generated (it may be important for the public to see if reissuance of a token is possible). But at the moment, reissuance is not possible due to the CT bug - but I think we are planning to try and fix this?

**Comment by nkostoulas** [comment]
Yep, I just added this for future reference. Wasn't sure if it belonged with the rest of the outputs, but since it's an asset as well it would make sense. Maybe just add a new label to differentiate.
