### ISSUE TITLE
Search by Address

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/ocean-explorer#4]

**Comment by nkostoulas** [comment]
This will require storing all the utxos of an address and then removing any that are spent.

**Comment by nkostoulas** [comment]
Address search should be added in the search bar.

**Comment by tomossomot** [comment]
All done [here](https://github.com/commerceblock/ocean-explorer/tree/add_addr_info).

Will include `/asset/:assetid` as assigned in [issue #20](https://github.com/commerceblock/ocean-explorer/issues/20) in this branch also.
